- hosts: master
  become: yes	
  tasks:
   - name: set name master
     shell: hostnamectl set-hostname 'k8-master'
- hosts: worker1
  become: yes
  tasks:
   - name: set name worker1
     shell: hostnamectl set-hostname 'k8-worker1'
- hosts: worker2
  become: yes
  tasks:
   - name: set name worker2
     shell: hostnamectl set-hostname 'k8-worker2'
- hosts: all
  become: yes
  tasks:
   - name: setup firewall rules
     shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
  
   - name: setup bridge
     shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes
   - name: swap off
     shell: swapoff -a
